name: Continuous Deployment to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@master

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install python-django
      
    - name: Generate HTML
      run: python2 gen.py
      
    - name: Move to deploy dir
      run: mkdir -p GHPAGES && mv index.html GHPAGES/
      
    - name: GitHub Pages Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: GHPAGES # The folder the action should deploy.
