name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Update
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install python-django
    - name: Generate HTML
      run: python2 gen.py
    - name: Move to deploy dir
      run: mkdir -p GHPAGES && mv index.html GHPAGES/
    - name: Run a multi-line script
      run: echo "foo bar"
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
          BUILD_DIR: GHPAGES
